crdt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('note/', include('note.urls')),
    path('notification/', include('notification.urls')),
]

note/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views 

app_name = 'note'

router = DefaultRouter()
router.register('', views.NoteViewSet)
router.register('tag/', views.TagViewSet)

urlpatterns = [
    path('share/', views.NoteShareRequestView.as_view(), name='share'),
    path('share/accept/', views.NoteShareAcceptView.as_view(), name='share-accept'),
    path('notes_view/', views.notes_view, name='notes-view'),
    path('list/', views.NotesView.as_view(), name='list'),
    path('list/shared/', views.SharedNotesView.as_view(), name='shared-list'),
    path('detail/<int:pk>/', views.note_detail_view, name='detail-view'),
    path('<int:pk>/', views.NoteViewSet.as_view({'get': 'retrieve'}), name='detail'),  
    path('commit/<int:note_id>/', views.NoteCommitView.as_view(), name='commit'),
    path('pull/<int:note_id>/', views.NotePullView.as_view(), name='pull'),
    path('commit-log/<int:note_id>/', views.CommitLogView.as_view(), name='commit-log'),
    path('commit-log-view/<int:note_id>/', views.commit_log_view, name='commit-log-view'),
    path('rollback/<int:version_id>/', views.RollbackView.as_view(), name='rollback'),
    path('stash/<int:note_id>/', views.NoteStashView.as_view(), name='stash'),
    path('stash-pop/<int:note_id>/', views.NoteStashPopView.as_view(), name='stash-pop'),
    path('', include(router.urls)),
    
     
]

notification/urls.py
from django.urls import path, include

from . import views 

app_name = 'notification'

urlpatterns = [
    path('', views.notification_list_view, name='list-view'),
    path('list/', views.NotificationView.as_view(), name='list'),
    path('read/<int:note_id>/', views.ReadNotificationView.as_view(), name='read'),
    path('delete/read/', views.DeleteReadNotifications.as_view(), name='delete-read'),
    path('delete/all/', views.ReadAllAndDeleteNotificationView.as_view(), name='delete-all'),
]

user/urls.py
from django.urls import path, include

from . import views 

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('follow/<int:user_pk>/', views.FollowView.as_view(), name='follow'),
    path('followings/', views.FollowingListView.as_view(), name='following-list'),
    path('followers/', views.FollowerListView.as_view(), name='follower-list'),
    
    path('follow-view/', views.follow_view, name='follow-view'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    email = models.EmailField(unique=True)
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)
    
    def __str__(self):
        return self.email

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from rest_framework import viewsets, status
from rest_framework.views import APIView
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.response import Response


from . models import *
from . serializers import * 


class RegisterView(APIView):
    permission_classes = []

    def post(self, request):
        data = request.data 
        serializer = RegisterSerializer(data=data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return JsonResponse({'msg': '회원가입 성공'}, status=status.HTTP_201_CREATED)
    
class LoginView(APIView):
    permission_classes = []

    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        data = request.data 
        serializer = LoginSerializer(data=data)
        serializer.is_valid(raise_exception=True)

        email = data.get('email')
        password = data.get('password')
        user = authenticate(username=email, password=password)
        if user is None:
            raise serializers.ValidationError("비밀번호 불일치")

        token = TokenObtainPairSerializer.get_token(user)
        access_token = str(token.access_token)
        refresh_token = str(token)

        response = Response({'access_token': access_token, 'refresh_token': refresh_token, 'user_id': user.id, 'username': user.username}, status=status.HTTP_200_OK)
        response.set_cookie('access_token', access_token)
        response.set_cookie('refresh_token', refresh_token)

        return response
    
class FollowView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, user_pk):
        try:
            following = User.objects.get(pk=user_pk)
        except User.DoesNotExist:
            return Response({'msg': '존재하지 않는 사용자를 팔로우 시도했습니다.'}, status=status.HTTP_404_NOT_FOUND)
        user = request.user 

        user.followings.add(following)

        return Response({'msg': '팔로우되었습니다.'}, status=status.HTTP_200_OK)
    
    def delete(self, request, user_pk):
        try:
            following = User.objects.get(pk=user_pk)
        except User.DoesNotExist:
            return Response({'msg': '존재하지 않는 사용자를 언팔로우 시도했습니다.'}, status=status.HTTP_404_NOT_FOUND)
        user = request.user 

        user.followings.remove(following)

        return Response({'msg': '언팔로우했습니다.'}, status=status.HTTP_200_OK)


class FollowingListView(APIView):
    def get(self, request):
        followings = request.user.followings.all()

        serializer = FollowingListSerializer(followings, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)

class FollowerListView(APIView):
    def get(self, request):
        followers = User.objects.filter(followings=request.user)

        serializer = FollowingListSerializer(followers, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)
    
def follow_view(request):
    render(request, 'user/follow.html')

user/templates/user/follow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        
    </script>
</head>
<body>
    <div id="followings">
        <h1>팔로잉</h1>
        <ul>
        </ul>
    </div>
    <div id="followers">

    </div>
</body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#notes-view').click(function(event) {
            $.ajax({
                type: 'GET',
                url: '/note/notes-view',
                headers: {
                    'Authorization': 'Bearer ' + access_token
                },
                success: function(data) {
                    console.log(data)
                }
            })
        })
        $('#login_form').submit(function(event) {
            event.preventDefault();

            var formData = {
                email: $('#email').val(),
                password: $('#password').val()
            };

            $.ajax({
                type: 'POST',
                url: '/user/login/',
                data: JSON.stringify(formData),
                contentType: 'application/json',
                success: function(data) {
                    var access_token = data.access_token;
                    var refresh_token = data.refresh_token;

                    console.log(access_token);
                },
                error: function(xhr, textStatus, errorThrown) {
                    console.error(errorThrown);
                }
            });
        });
    });
</script>
<body>
    <form id="login_form" method="post">
        {% csrf_token %}
        <input type="text" id="email" name="email"/>
        <input type="password" id="password" name="password"/>
        <button type="submit">로그인</button>
    </form>

    <a href="{% url 'notification:list-view' %}">알림창 보기</a>
    <a href="{% url 'note:notes-view' %}" id="notes-view">내 노트 보기</a>
    <a href="{% url 'user:follow-view' %}">내 친구 보기</a>
</body>
</html>