crdt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('note/', include('note.urls')),
    path('notification/', include('notification.urls')),
]

note/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views 

app_name = 'note'

router = DefaultRouter()
router.register('', views.NoteViewSet)
router.register('tag/', views.TagViewSet)

urlpatterns = [
    path('share/', views.NoteShareRequestView.as_view(), name='share'),
    path('share/accept/', views.NoteShareAcceptView.as_view(), name='share-accept'),
    path('notes_view/', views.notes_view, name='notes-view'),
    path('list/', views.NotesView.as_view(), name='list'),
    path('list/shared/', views.SharedNotesView.as_view(), name='shared-list'),
    path('detail/<int:pk>/', views.note_detail_view, name='detail-view'),
    path('<int:pk>/', views.NoteViewSet.as_view({'get': 'retrieve'}), name='detail'),  
    path('commit/<int:note_id>/', views.NoteCommitView.as_view(), name='commit'),
    path('pull/<int:note_id>/', views.NotePullView.as_view(), name='pull'),
    path('commit-log/<int:note_id>/', views.CommitLogView.as_view(), name='commit-log'),
    path('commit-log-view/<int:note_id>/', views.commit_log_view, name='commit-log-view'),
    path('rollback/<int:version_id>/', views.RollbackView.as_view(), name='rollback'),
    path('stash/<int:note_id>/', views.NoteStashView.as_view(), name='stash'),
    path('stash-pop/<int:note_id>/', views.NoteStashPopView.as_view(), name='stash-pop'),
    path('', include(router.urls)),
    
     
]

note/models.py
from django.db import models

from user.models import User

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name 

class Note(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_notes')
    shared_users = models.ManyToManyField(User, blank=True, related_name='shared_notes')
    tags = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

class Version(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    next_version = models.OneToOneField('self', related_name='prev', null=True, blank=True, on_delete=models.SET_NULL)
    prev_version = models.OneToOneField('self', related_name='next', null=True, blank=True, on_delete=models.SET_NULL)    

class StashedVersion(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

note/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from rest_framework import viewsets, status
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from . models import *
from . serializers import * 

from notification.models import *
from notification.views import save_notification

# Create your views here.

class NoteViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = NoteSerializer
    queryset = Note.objects.all().order_by('created_at')

    def create(self, request):
        serializer = self.serializer_class(data=request.data, context={'user': request.user})
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return JsonResponse({'msg': '노트가 생성되었습니다.'}, status=status.HTTP_201_CREATED)


def notes_view(request):
    permission_classes = [AllowAny]
    return render(request, 'note/note-list.html')

def note_detail_view(request, pk):
    permission_classes = [AllowAny]

    note = Note.objects.get(pk=pk)
    current_version = Version.objects.filter(note=note).latest('created_at')
    return render(request, 'note/note-detail.html', {'note': note, 'current_version': current_version})

class NotesView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        notes = Note.objects.filter(created_by=request.user)
        serializer = NoteSerializer(notes, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)
    
class NoteCommitView(APIView):
    def post(self, request, note_id):
        note = Note.objects.get(id=note_id)
        user = request.user 

        serializer = NoteCommitSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        new_content = serializer.validated_data['new_content']

        current_version = Version.objects.get(id=serializer.validated_data['current_version'].id)
        if current_version.next_version:
            print("충돌!")
            return 

        print('prev version: ', current_version.id)
        new_version = Version.objects.create(note=note, content=new_content, user=user, prev_version=current_version, next_version=None)
        current_version.next_version = new_version         
        current_version.save()
        note.content = new_content 
        note.save() 

        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            f"note{note.id}", {
                "type": "commit_notify",
                "data": user.username
            }
        )
        
        return Response({'current_version': new_version.id}, status=status.HTTP_200_OK)

class NotePullView(APIView):
    def post(self, request, note_id):
        current_version = Version.objects.get(id=request.data.get('current_version'))
        latest_version = Version.objects.filter(note=note_id).latest('created_at')

        if current_version.id == latest_version.id:
            return Response({'msg': '이미 최신 버전으로 풀된 상태입니다'}, status=status.HTTP_200_OK)
        
        serializer = VersionSerializer(latest_version)

        return Response(serializer.data, status=status.HTTP_200_OK)
    
class NoteStashView(APIView):
    def post(self, request, note_id):
        note = Note.objects.get(id=note_id)
        content = request.data.get('content')
        user = request.user

        stash = StashedVersion.objects.create(note=note, content=content, user=user)
        return Response({'msg': '스테이시 성공'}, status=status.HTTP_200_OK)
    
class NoteStashPopView(APIView):
    def post(self, request, note_id):
        note = Note.objects.get(id=note_id)
        user = request.user

        stash = StashedVersion.objects.filter(note=note, user=user).latest('created_at')

        stash.delete()

        return Response({'stash': stash.content}, status=status.HTTP_200_OK)
    
class SharedNotesView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        notes = Note.objects.filter(shared_users=request.user)
        serializer = NoteSerializer(notes, many=True)
        
        return Response(serializer.data, status=status.HTTP_200_OK)


class TagViewSet(viewsets.ModelViewSet):
    serializer_class = TagSerializer
    queryset = Tag.objects.all()

class NoteShareRequestView(APIView):
    def post(self, request):
        data = request.data 
        serializer = NoteShareRequestSerializer(data=data)
        serializer.is_valid(raise_exception=True)

        shared_with = data.get('shared_with')
        note = Note.objects.get(pk=data.get('note'))
        for recipient in shared_with:
            save_notification(NotificationType.NOTE_SHARE_REQUEST, request.user.pk, recipient, note)

        return JsonResponse({'msg': '노트 공유를 완료했습니다.'}, status=status.HTTP_200_OK)
    
class NoteShareAcceptView(APIView):
    def post(self, request):
        print(request.data)
        data = request.data 
        serializer = NoteShareAcceptSerializer(data=data, context={'user': request.user})
        serializer.is_valid(raise_exception=True)
        serializer.save()

        shared_by = data.get('shared_by')
        note = Note.objects.get(pk=data.get('note'))
        save_notification(NotificationType.NOTE_SHARE_ACCEPT, request.user.pk, shared_by, note)

        return JsonResponse({'msg': '노트 공유를 수락했습니다.'}, status=status.HTTP_200_OK)
    
def commit_log_view(request, note_id):
    versions = Version.objects.filter(note=note_id).order_by('created_at')
    return render(request, 'note/commit-log.html', {'versions': versions, 'note_id': note_id})

class CommitLogView(APIView):
    def get(self, request, note_id):
        versions = Version.objects.filter(note=note_id).order_by('created_at')

        serializer = VersionSerializer(versions, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)
    
class RollbackView(APIView):
    def post(self, request, version_id):
        rollback_version = Version.objects.get(id=version_id)

        delete_version = rollback_version.next_version
        while delete_version:
            next_version = delete_version.next_version
            delete_version.delete()
            delete_version = next_version 
        
        rollback_version.next_version = None
        rollback_version.save()

        note = rollback_version.note 
        note.content = rollback_version.content
        note.save()

        return Response({'msg': '삭제 성공'}, status=status.HTTP_200_OK)
        

note/templates/note/commit-log.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // 쿠키 이름이 일치하는 경우 값을 얻어냅니다.
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

document.addEventListener('DOMContentLoaded', function() {
    var access_token = getCookie('access_token');
    var ulCommitLog = document.getElementById('commit-log');

    $('#rollback').click(function() {
        var selectedVersion = $('input[name="selectedVersion"]:checked').val();

        if(!selectedVersion) {
            alert('롤백할 버전을 선택하세요.');
            return; 
        }

        $.ajax({
            url: '/note/rollback/' + selectedVersion + '/',
            type: 'POST',
            headers: {
                'Authorization': 'Bearer ' + access_token  
            },
            success: function(data) {
                console.log(data);
                location.reload();
            }
        });
    });

    var note_id = $(".note_id").data("note-id");
    
});

    </script>
</head>
<body>
    <div id="container">
        <ul id="commit-log">
            {% for version in versions %}
                <li>
                    <input type="radio" name="selectedVersion" value="{{ version.id }}">
                    {{ version.id }} 작성자: {{ version.user }} 커밋날짜: {{ version.created_at }}
                </li>
            {% endfor %}
            </ul>
        <div class="note_id" style="display:none;">{{ note_id }}</div>

        <button id="rollback">해당 버전으로 롤백하기</button>
    </div>
</body>
</html>

note/templates/note/note-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsdiff/4.0.1/diff.min.js"></script>
    <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css'>
    <style>
        * {font-family: Pretendard,'Noto Sans KR', sans-serif;}
        .container {
            margin: 0 auto;
            width:512px;
        }

        #editor-container {
            width: 512px;
        }
        #editor {
            height:200px;
        }

        button {
            cursor: pointer;
            background-color: #416efc;
            color:white;
            border-radius: 10px;
            text-decoration: none;
            border:none;
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);
            width:50px;
            height:30px;
            margin-right:10px;
        }

        #buttons {
            float:right;
            margin-top:15px;
        }
    </style>
    <script type="module">
        import * as Y from 'https://esm.sh/yjs@13'
        </script>
    <script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // 쿠키 이름이 일치하는 경우 값을 얻어냅니다.
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

document.addEventListener('DOMContentLoaded', function() {

    var access_token = getCookie('access_token');
    var note_id = $(".note_id").data("note-id");
    console.log("note_id: ", note_id);
    const socket = new WebSocket(`ws://127.0.0.1:8000/ws/note/?token=${access_token}&note_id=${note_id}`);

    socket.addEventListener('message', (event) => {
        
        const data = JSON.parse(event.data);
        console.log('서버로부터 데이터 수신:', data);

        if(data.type == "commit_notify") {
            var commit_notification = document.getElementById('commit-notification');
            commit_notification.innerText = data.data + "님이 지금 커밋하셨습니다.";
            return;
        }

        if(data.type == "disconnect_notify") {
            const username = data.username;
            console.log()
            
            const user_lis = $('.' + username);

            console.log("삭제!!!");
            user_lis.remove();
                

            return;
        }

        if(data.current_users) {
            const currentUsers = data.current_users;
            for(let i = 0; i < currentUsers.length; i++) {
                const user_li = document.createElement('li');
                user_li.classList.add(currentUsers[i]);
                user_li.textContent = currentUsers[i];
                document.getElementById('active-users').appendChild(user_li);
                console.log(currentUsers[i])
            }

            return;
        }

        const user_li = document.createElement('li');
        user_li.classList.add(data.data.username);
        user_li.textContent = data.data.username;
        document.getElementById('active-users').appendChild(user_li);
    // 여기에서 데이터를 처리하거나 화면에 표시할 수 있습니다.
    });

    // WebSocket이 닫히면 실행됩니다.
    socket.addEventListener('close', (event) => {
    console.log('WebSocket 연결이 닫혔습니다.');
    });

    $('#commit').click(function(){
        var version_id = $(".version_id").data("version-id");
        var formData = {
            new_content: quill.root.innerHTML,
            current_version: version_id
        }

        $.ajax({
            url: '/note/commit/' + note_id + '/',
            type: 'POST',
            data: formData,
            headers: {
                 'Authorization': 'Bearer ' + access_token            
            },
            success: function(data) {
                console.log(data);
                $('.version_id').data("version-id", data.current_version);
            }
        });
    });

    $('#pull').click(function() {
        var version_id = $(".version_id").data("version-id");
        var formData = {
            current_version: version_id
        }

        $.ajax({
            url: '/note/pull/' + note_id + '/',
            type: 'POST',
            data: formData,
            headers: {
            'Authorization': 'Bearer ' + access_token            
            },
            success: function(data) {
                console.log(data);
                $('.version_id').data("version-id", data.current_version)
                
                var textarea = document.getElementById('editor');
                var previousContent = textarea.value;

                var newContent = data.content;

                if(previousContent == '') {
                    quill.setContents(newContent);
                    return;
                }
                var diff = Diff.diffChars(previousContent, newContent);
                var updatedContent = '';

                diff.forEach(function(part){
                    if(part.added || part.removed) {
                        updatedContent += '<span style="background-color: lightgreen;">' + part.value + '</span>';

                    } else {
                        updatedContent += part.value;
                    }
                });

                //textarea.innerHTML = updatedContent;
                quill.setText(updatedContent);
            }
        });
    });

    $('#stash').click(function() {
        var formData = {
            'content': quill.root.innerHTML,
        }

        $.ajax({
            url: '/note/stash/' + note_id + '/',
            type: 'POST',
            data: formData,
            headers: {
            'Authorization': 'Bearer ' + access_token            
            },
            success: function(data) {
                console.log(data);
                $('.version_id').data("version-id", data.current_version)
                var modal = document.getElementsByClassName("modal")[0];
                var modal_content = document.getElementsByClassName("modal-content")[0];
                var modal_h3 = document.getElementById("modal-h3");
                var p = document.getElementsByTagName("p")[0];
                modal.style.display = "block";
                p.innerHTML = data.content;

                window.onclick = function(event) {
                    if (event.target == modal) {
                        modal.style.display = "none";
                    }
                }
            }
        });
    });

    $('#stash-pop').click(function() {
        var version_id = $(".version_id").data("version-id");
        var formData = {
            current_version: version_id
        }

        alert("스테이시 팝을 하면 스테이시 내용이 사라집니다.");

        $.ajax({
            url: '/note/stash-pop/' + note_id + '/',
            type: 'POST',
            data: formData,
            headers: {
            'Authorization': 'Bearer ' + access_token            
            },
            success: function(data) {
                console.log(data);
                $('.version_id').data("version-id", data.current_version)
                var textarea = quill.root.innerHTML;
                var previousContent = textarea.value;

                var newContent = data.content;

                var diff = Diff.diffChars(previousContent, newContent);
                var updatedContent = '';

                diff.forEach(function(part){
                    if(part.added || part.removed) {
                        updatedContent += '<span style="background-color: lightgreen;">' + part.value + '</span>';

                    } else {
                        updatedContent += part.value;
                    }
                });

                textarea.innerHTML = updatedContent;
            }
        });
    });
});


    </script>
</head>
<body>
    <div class="container">
        <h1>{{ note.title }}</h1>
        <div id="editor-container">
            <div id="editor">{{ note.content | safe }}</div>
        </div>
        
        <div id="buttons">
            <button id="commit">커밋</button>
            <button id="pull">풀</button>
            <button id="stash">스테이시</button>
            <button id="stash-pop">스테이시 팝</button>
        </div>
        <div id="commit-log">
            <a href="{% url 'note:commit-log-view' note_id=note.id %}">커밋 히스토리 보기</a>
            <a href="">스테이시한 내용 보기</a>
        </div>

        <div class="version_id" data-version-id="{{ current_version.id }}" style="display:none;"></div>
        <div class="note_id" data-note-id="{{ note.id }}" style="display:none;"></div>
        <div id="commit-notification"></div>
        
        <h3>공유 사용자 목록</h3>
        <ul>
            {% for user in note.shared_users.all %}
                <li>{{ user.username }}</li>
            {% endfor %}
        </ul>
        <h3>접속 중 사용자</h3>
        <ul id="active-users">

        </ul>
        <div class="modal">
            <div class="modal-content">
              <span class="close-button">&times;</span>
              <h3 id="modal-h3">스테이시 내용</h3>
                <p>

                </p>
            </div>
          </div>
    </div>

    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script>
        var quill = new Quill('#editor', {
            theme: 'snow'
        });
    </script>
</body>
</html>

note/templates/note/note-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // 쿠키 이름이 일치하는 경우 값을 얻어냅니다.
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

$(document).ready(function() {
    var access_token = getCookie('access_token');


    $('.close').click(function() {
        var modal = document.getElementById('followingModal');
        modal.style.display = 'none';
    });
    window.onclick = function(event) {
        var modal = document.getElementById('followingModal');
        if (event.target === modal) {
            modal.style.display = 'none';
        }
    };

    $.ajax({
        url: '/note/list/shared',
        type: 'GET',
        headers: {
            'Authorization': 'Bearer ' + access_token            
        },
        success: function(data) {
            var notes = $('#shared-notes');
            data.forEach(function(note) {
                var noteLink = $('<a>', {
                    'class': 'note',
                    'id': note.id,
                    'href': '/note/detail/' + note.id + '/', // 노트 디테일 페이지의 URL을 동적으로 생성
                    'text': note.title
                });

                notes.append(noteLink);
                notes.append('<br>');
            });
        }
    });

    $.ajax({
        url: '/note/list/',
        type: 'GET',
        headers: {
            'Authorization': 'Bearer ' + access_token
        },
        success: function(data) {
            var notes = $('#notes');
            data.forEach(function(note) {
                var noteLink = $('<a>', {
                    'class': 'note',
                    'id': note.id,
                    'href': '/note/detail/' + note.id + '/', // 노트 디테일 페이지의 URL을 동적으로 생성
                    'text': note.title
                });

                notes.append(noteLink);
                notes.append('<button class="share" id="' + note.id + '">공유하기</button>');
                notes.append('<br>');
            });
        }
    });
    var modal = document.getElementById('followingModal');
    modal.style.display = 'block';

    $.ajax({
        type: 'GET',
        url: '/user/followings/',
        headers: {
            'Authorization': 'Bearer ' + access_token
        },
        success: function(data) {
            var followingList = $('#followingList');
            followingList.empty();
            data.forEach(function(user) {
                followingList.append('<li><input type="radio" name="selectedUser" value="' + user.id + '"/>' + user.username + '</li>');
                
            });
        },
        error: function(xhr, textStatus, errorThrown){
            console.error('error: ', errorThrown);
        }
    });
    $(document).on('click', '.share', function(event) {
        var access_token = getCookie('access_token');
        var selectedNoteId = $(this).attr('id');
        var selectedUserId = $('input[name="selectedUser"]:checked').val();
        console.log('selectedNoteId:',selectedNoteId);
        console.log('selectedUserId:', [selectedUserId]);

        if(!selectedUserId) {
            alert('노트 공유할 사용자 선택하셈');
            return;
        }
        var formData = {
            'note': selectedNoteId,
            'shared_with': [selectedUserId]
        };

        $.ajax({
            type: 'POST',
            url: '/note/share/',
            headers: {
                'Authorization': 'Bearer ' + access_token
            },
            data: JSON.stringify(formData),
            contentType: 'application/json',
            success: function(response) {
                alert('노트 공유 성공!');
                console.log(response);
            },
            error: function(xhr, textStatus, errorThrown) {
                console.error('Error:' , errorThrown);
            }
        });
    });
});



    </script>
</head>
<body>
    <div id="notes">

    </div>

    <div id="followingModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>팔로잉 목록</h2>
            <ul id="followingList"></ul>
        </div>
    </div>

    <div id="shared-notes">
        <h3>공유 노트</h3>

    </div>
</body>
</html>

note/templates/note/tmp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsdiff/4.0.1/diff.min.js"></script>
    <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css'>
    <style>
        * {font-family: Pretendard,'Noto Sans KR', sans-serif;}
        .container {
            margin: 0 auto;
            width:512px;
        }

        #editor-container {
            width: 512px;
        }
        #editor {
            height:200px;
        }

        button {
            cursor: pointer;
            background-color: #416efc;
            color:white;
            border-radius: 10px;
            text-decoration: none;
            border:none;
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);
            width:50px;
            height:30px;
            margin-right:10px;
        }

        #buttons {
            float:right;
            margin-top:15px;
        }
    </style>

    <script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // 쿠키 이름이 일치하는 경우 값을 얻어냅니다.
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

document.addEventListener('DOMContentLoaded', function() {

    const ydoc = new Y.Doc();

    var access_token = getCookie('access_token');
    var note_id = $(".note_id").data("note-id");

    const socket = new WebSocket(`ws://127.0.0.1:8000/ws/note/?token=${access_token}&note_id=${note_id}`);

    socket.addEventListener('message', (event) => {
        
        const data = JSON.parse(event.data);
        console.log('서버로부터 데이터 수신:', data);

        // 다른 유저 접속 끊으면
        if(data.type == "disconnect_notify") {
            const username = data.username;
            console.log()
            
            const user_lis = $('.' + username);

            console.log("삭제!!!");
            user_lis.remove();
                

            return;
        }

        if(data.current_users) {
            const currentUsers = data.current_users;
            for(let i = 0; i < currentUsers.length; i++) {
                const user_li = document.createElement('li');
                user_li.classList.add(currentUsers[i]);
                user_li.textContent = currentUsers[i];
                document.getElementById('active-users').appendChild(user_li);
                console.log(currentUsers[i])
            }

            return;
        }

        const user_li = document.createElement('li');
        user_li.classList.add(data.data.username);
        user_li.textContent = data.data.username;
        document.getElementById('active-users').appendChild(user_li);
    });

    // WebSocket이 닫히면 실행됩니다.
    socket.addEventListener('close', (event) => {
    console.log('WebSocket 연결이 닫혔습니다.');
    });


    $.ajax({
        url: '/note/' + note_id + '/',
        type: 'GET',
        success: function(response) {
            var note_id = response.data.id;
            var title = response.data.title;
            var content = response.data.content;
            var shaned_users = response.data.shared_users;

            $("h1").text(title);
            $("#editor").html(content);
            var sharedUsersList = $("#shared-users");
            sharedUsersList.empty(); // 기존 목록을 지우고
            for (var i = 0; i < shared_users.length; i++) {
                sharedUsersList.append("<li>" + shared_users[i].username + "</li>");
            }
        }
    })
   

    
});


    </script>
</head>
<body>
    <div class="container">
        <h1></h1>
        <div id="editor-container">
            <div id="editor"></div>
        </div>

        <div id="commit-log">
            <a href="{% url 'note:commit-log-view' note_id=note.id %}">커밋 히스토리 보기</a>
        </div>
        
        <h3>공유 사용자 목록</h3>
        <ul>
                <li></li>
        </ul>
        <h3>접속 중 사용자</h3>
        <ul id="active-users">

        </ul>
    </div>

    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script>
        var quill = new Quill('#editor', {
            theme: 'snow'
        });
    </script>
</body>
</html>